github: [youngbee08]       # Up to 4 GitHub Sponsors-enabled usernames
# patreon: zenithdevtech                              # Single Patreon username
# open_collective:               # Single Open Collective username
# ko_fi:                                  # Single Ko-fi username
# tidelift: npm/babel                               # Platform-name/package-name
# community_bridge: cloud-foundry                  # Project-name
# liberapay:                               # Single Liberapay username
# issuehunt:                               # Single IssueHunt username
# lfx_crowdfunding: cloud-foundry                  # Project-name
# polar:                                   # Single Polar username
# buy_me_a_coffee:                         # Single Buy Me a Coffee username
# thanks_dev:                               # Single thanks.dev username
# custom: []  # Up to 4 custom URLs
